import { AppData } from '@/types';

export const initialData: AppData = {
  listings: [
    {
      id: '1',
      kind: 'cheap-meal',
      title: 'Budget Idli Combo',
      foodName: '4 Idlis + Chutney',
      description: 'Fresh breakfast combo from a local stall. Quick pickup and great for students.',
      address: 'CMH Road, Indiranagar, Bengaluru',
      quantity: '18 plates',
      price: 35,
      isVeg: true,
      availableFrom: '07:00 AM',
      availableTill: '10:30 AM',
      contact: '+91 90000 11111',
      pickupInstructions: 'Ask for the student special at the counter.',
      createdAt: new Date().toISOString(),
      ratingAverage: 4.4,
      ratingCount: 12,
      reportCount: 0,
      verified: true,
      lastConfirmedAt: new Date().toISOString(),
      imageUri: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=1200&auto=format&fit=crop'
    },
    {
      id: '2',
      kind: 'free-meal',
      title: 'Community Rice & Sambar',
      foodName: 'Rice, sambar, pickle',
      description: 'Free meal support for anyone who needs a filling lunch.',
      address: 'Near KR Market Metro Exit, Bengaluru',
      quantity: '40 meals',
      price: 0,
      isVeg: true,
      availableFrom: '12:00 PM',
      availableTill: '02:30 PM',
      contact: '+91 98888 22222',
      pickupInstructions: 'Queue on the left side; bring your own container if possible.',
      createdAt: new Date().toISOString(),
      ratingAverage: 4.8,
      ratingCount: 8,
      reportCount: 0,
      verified: true,
      lastConfirmedAt: new Date().toISOString(),
      imageUri: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=1200&auto=format&fit=crop'
    },
    {
      id: '3',
      kind: 'event',
      title: 'Friday Langar',
      foodName: 'Langar meal',
      description: 'Open community meal served every Friday evening.',
      address: 'Ulsoor Gurudwara, Bengaluru',
      quantity: '200 servings',
      price: 0,
      isVeg: true,
      availableFrom: '07:00 PM',
      availableTill: '09:00 PM',
      contact: '+91 97777 33333',
      pickupInstructions: 'Shoes outside. Family-friendly and walk-ins welcome.',
      createdAt: new Date().toISOString(),
      ratingAverage: 4.9,
      ratingCount: 24,
      reportCount: 0,
      verified: true,
      lastConfirmedAt: new Date().toISOString(),
      eventType: 'gurudwara',
      organizerName: 'Seva Volunteers',
      expectedCrowd: 'High',
      isRecurring: true,
      imageUri: 'https://images.unsplash.com/photo-1464306076886-da185f6a9d05?q=80&w=1200&auto=format&fit=crop'
    }
  ],
  ratings: [],
  reports: []
};
